services:
  landing-mayorista-vb:
    build:
      context: .
    container_name: landing-mayorista-vb
    restart: unless-stopped
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: mi-red-nginx
